# Generated by Django 5.0.7 on 2024-11-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendname', models.ForeignKey(help_text='Reference to the receiving user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_friendname', to='users.user')),
                ('username', models.ForeignKey(help_text='Reference to the initiating user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_username', to='users.user')),
            ],
        ),
    ]
