# Base image
FROM alpine:3.19

# RUN apk update
# Install MariaDB
# RUN apk update && \
#     apk add --no-cache mariadb mariadb-client && \
#     mkdir -p /run/mysqld && \
#     chown -R mysql:mysql /run/mysqld && \
#     mkdir -p /var/lib/mysql && \
#     chown -R mysql:mysql /var/lib/mysql

# Default command to start MariaDB
# CMD ["mysqld", "--user=mysql"]
# CMD ["tail", "-f", "/dev/null"]