# Generated by Django 5.0.7 on 2024-11-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='User unique id', max_length=150, unique=True)),
                ('profile_img', models.IntegerField(choices=[(0, '피카츄'), (1, '파이리'), (2, '이상해씨'), (3, '꼬부기'), (4, '이브이'), (5, '잠만보'), (6, '뮤'), (7, '메타몽')], default=0, help_text='Profile image ID for the user, selectable from predefined options.')),
                ('status', models.IntegerField(choices=[(0, '오프라인'), (1, '온라인')], default=0, help_text='User activity status')),
                ('exp', models.IntegerField(default=0, help_text='Experience points accumulated by the user.')),
                ('win_cnt', models.IntegerField(default=0, help_text='User win count')),
                ('lose_cnt', models.IntegerField(default=0, help_text='User lose count')),
                ('status_msg', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="User custom status message, default is '텍스트를 입력해주세요'", max_length=100)),
                ('macrotext1', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="Macro text 1, default is '텍스트를 입력해주세요'.", max_length=100)),
                ('macrotext2', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="Macro text 2, default is '텍스트를 입력해주세요'.", max_length=100)),
                ('macrotext3', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="Macro text 3, default is '텍스트를 입력해주세요'.", max_length=100)),
                ('macrotext4', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="Macro text 4, default is '텍스트를 입력해주세요'.", max_length=100)),
                ('macrotext5', models.CharField(blank=True, default='텍스트를 입력해주세요', help_text="Macro text 5, default is '텍스트를 입력해주세요'.", max_length=100)),
            ],
        ),
    ]
