# Base image
FROM alpine:3.19

# # Install wordpress
# RUN apk update && \
# 	apk add --no-cache mariadb mariadb-client mariadb-server-utils pwgen && \
# 	rm -f /var/cache/apk/*

# # Default command to start MariaDB
# CMD ["php-fpm7", "-F"]
