# Base image
FROM alpine:3.19

# # Install niginx
# RUN apk update && \
# 	apk add --no-cache nginx && \
# 	mkdir -p /run/nginx

# # Default command to start MariaDB
# CMD ["nginx", "-g", "daemon off;"]
