# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    # SSL 설정 (환경 변수를 참조)
    ssl_certificate /etc/nginx/.key/Pri/nginx.crt;
    ssl_certificate_key /etc/nginx/.key/Pri/nginx.key;

    # Everything is a 404
    location / {
        return 404;
    }

    # You may need this to prevent return 404 recursion.
    location = /404.html {
        internal;
    }
}
